### ISSUE TITLE
Desktop - testimonials 

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#20]
Change font-weight semibold of the testimonial name
the div is cutting at the bottom

![image](https://cloud.githubusercontent.com/assets/1996761/26650592/8a4e7930-4667-11e7-86f5-cbb67d79379a.png)
dots should be orange active and light grey for inactive

**Comment by iamjamielobo** [comment]
Done

**Comment by alliv8** [comment]
alignment is off
![image](https://cloud.githubusercontent.com/assets/1996761/26671819/8364204e-46d4-11e7-9c95-36c98f8f7a35.png)

**Comment by iamjamielobo** [comment]
done
