### ISSUE TITLE
/faqs - header is wrong

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#31]
design is updated

![image](https://cloud.githubusercontent.com/assets/1996761/26760771/c19a7752-493e-11e7-9ca0-84dd5b1aa570.png)

**Comment by iamjamielobo** [comment]
done

**Comment by alliv8** [comment]
also add a # in the URL that decides which tab is active. there are two CTAs in the homepage that lead to these sections respectively.
