### ISSUE TITLE
contact us form - proweb

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#34]
Please use default contact us form from Proweb.

----
Gelnova Laboratories (I) Pvt. Ltd.
C-125 TTC Industrial Area, Mahape,
Navi Mumbai - 400703
[Map Link]
https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3770.205287097542!2d73.031262!3d19.098648000000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c0ec55555555%3A0xbcfa21274c7c2865!2sGelnova+Laboratories+India+Pvt.+Ltd!5e0!3m2!1sen!2sin!4v1432898506099
----
+91 8097055433
----
info@turmgel.com

**Comment by alliv8** [comment]
![image](https://user-images.githubusercontent.com/1996761/26998287-95992d6e-4d9f-11e7-8a91-deaf5ea0855f.png)


still not updated @vickykamble

**Comment by ghost** [comment]
Done
