### ISSUE TITLE
use the SVGs i provided. You haven't updated them

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#37]
For the active state, apply

fill: @orange
stroke: @orange

Currently, when the back pain icon is selected, you get a brown stroke on it.

**Comment by alliv8** [comment]
Thiis only applies for the feature circles I think.

**Comment by iamjamielobo** [comment]
done
some of the svgs werent in the folder so i reused them

**Comment by alliv8** [comment]
User number-sold.png here

![image](https://user-images.githubusercontent.com/1996761/26940579-d3f7f0f2-4c98-11e7-89dd-4a1585be70b8.png)
