### ISSUE TITLE
Benefit #3 Text

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#4]
ORAL HYGIENE 
Over 600 types of bacteria are present in the average mouth! As food particles breakdown in the mouth, some of these bacteria cause foul odours. At night, when the mouth is inactive and exposed to less oxygen,  the odour gets worse, causing "morning breath".

While brushing helps remove food particles from the mouth, it does not suffice to prevent bad breath. Chances are that some food particles will still remain in hard to reach places, allowing germs to proliferate, and causing tooth decay, gum diseases, mouth ulcerations, and other inflammatory and infectious diseases of the oral cavity. 

The natural antibacterial action of the Turmeric in Turmgel, reduces the bacterial load in the oral cavity. This results in the elimination of the bacteria responsible for bad breath, including those responsible for dental caries, gingivitis and periodontitis. The natural anti-inflammatory properties also reduce swelling and redness. Regular use of Turmgel prevents recurrence of dental problems. 

Recommended dosage:  
For dental caries, severe gingivitis and periodontitis: 4 lozenges a day, until remission; Maintenance dose 2 lozenges a day 
For general oral hygiene and treatment of bad breath: 2 lozenges a day

**Comment by iamjamielobo** [comment]
done
