### ISSUE TITLE
Add line mentioning regarding quantity restriction on trial pack

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#55]
This is there in marvel on cart page

It's a red line under the product in the cart.

**Comment by alliv8** [comment]
![image](https://user-images.githubusercontent.com/1996761/27004352-978ef4d8-4e25-11e7-953a-6ce125ffb3df.png)

**Comment by ghost** [comment]
This would be pain to add. Instead i made quantity input 1

**Comment by alliv8** [comment]
ok cool, works for now
