### ISSUE TITLE
Add line mentioning contact us for more info on cart page

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#56]
It's there in marvel. You can implement how you deem fit

**Comment by alliv8** [comment]
![image](https://user-images.githubusercontent.com/1996761/27004349-8b6d0294-4e25-11e7-88ec-cfc687187718.png)

**Comment by alliv8** [comment]
If this is hard to do, let's figure what else we can do.

**Comment by ghost** [comment]
Done
