### ISSUE TITLE
Product image in cart clipping

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#58]
http://turmgel.com/new/wp-content/uploads/2017/05/trial-pack-180x148.png
http://turmgel.com/new/wp-content/uploads/2017/05/family-pack-180x180.png

Should I give you updated image for both?

**Comment by alliv8** [comment]
https://github.com/iamjamielobo/turmgel-website/commit/74e0dde958a362091c569bd5b6b6d6f5e3e73de4

Here, updated images pushed

**Comment by ghost** [comment]
changed
