### ISSUE TITLE
Mobile / Desktop - Vertical align images in features section

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#6]
Also take the margins from the 2nd feature block since it has height 100px and rest are less.

**Comment by alliv8** [comment]
![image](https://cloud.githubusercontent.com/assets/1996761/26649617/391e2eaa-4664-11e7-98e6-a7f75421df2f.png)


Dash is far away from mobile and desktop both

**Comment by iamjamielobo** [comment]
done
