### ISSUE TITLE
Design of Cart Page

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#63]
This is what's live
![image](https://user-images.githubusercontent.com/1996761/27004549-5d21022a-4e28-11e7-9ceb-3e15a68ffa84.png)

This is how I gave it in design
![image](https://user-images.githubusercontent.com/1996761/27004555-7725649a-4e28-11e7-94d5-b7aea4f3f0ac.png)

> Can we get rid of the cart totals section here

> And the background of the cart contents is white, only the header here is light greyish-brown

**Comment by alliv8** [comment]
I had made this section from default woocommerce layout page ~

**Comment by ghost** [comment]
updated
