### ISSUE TITLE
/technology wrapper issue

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#66]
![image](https://user-images.githubusercontent.com/1996761/27004694-5b379a7a-4e2b-11e7-8aaa-898cecc8579e.png)

This is how it's in static ^^

**Comment by alliv8** [comment]
![image](https://user-images.githubusercontent.com/1996761/27004699-75f78230-4e2b-11e7-8620-976e367f9fde.png)

this is on /new

**Comment by ghost** [comment]
Done
