### ISSUE TITLE
Checkout - Replace Check payments dummy text

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#69]
![image](https://user-images.githubusercontent.com/1996761/27024542-8f572704-4f74-11e7-832f-ae5b5e0998d2.png)

Will have to get actual content from client for this.

**Comment by alliv8** [comment]
COMMENT OUT BANK TRANSFER & CHECK PAYMENTS OPTIONS. Spoke to Sanaeya, they don't want it

**Comment by ghost** [comment]
changed options
