### ISSUE TITLE
Mobile & Desktop - Products remove padding-top between product name and lorem ipsum

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#7]
![image](https://cloud.githubusercontent.com/assets/1996761/26649662/5a4e48ee-4664-11e7-9a73-d99740fe6b94.png)

Mobile

**Comment by alliv8** [comment]
![image](https://cloud.githubusercontent.com/assets/1996761/26650137/18633316-4666-11e7-8315-28cb23d4128d.png)

Desktop

**Comment by iamjamielobo** [comment]
done
