### ISSUE TITLE
/technology  - Page FAQ

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#70]
## **Technology Pag FAQ**

**What is the buccal route for drug delivery?** 
The buccal route refers to delivery of medicines from the floor of the mouth. There are two types: 
(a) Placing the medication on the tongue (buccal absorption)  
(b) Placing the medication below the tongue (sublingual)
 
**Why buccal absorption?**
Certain medicines get destroyed by the presence of food and enzymes present in our stomachs, resulting in a loss of important medicinal properties.  Such medicines then need to be taken in higher dosages which results in diminished health benefits and increased side effects. Therefore, alternate routes of administration that can by-pass the stomach, such as buccal absorption, are used. 
 
**Is buccal absorption efficient?** 
Yes, certainly. In fact, there are several products that are delivered through this route. Buccal absorption provides instant relief, as the absorption from mouth cavity is very rapid, provided that the product is developed in a manner that is suitable for buccal absorption. 
 
**How does buccal absorption result in instant action?** 
Buccal mucosa is made up of soft tissues, and is rich in blood supply. This is the reason our mouth cavities are always reddish. Pale mouth cavities signify low levels of red blood cells in the body. When the medicament is placed on the floor of the mouth, the high concentration of the drug immediately mixes with the saliva  and gets solubilized. As it dissolves, the high permeability in the mouth allows it to quickly enter the blood stream, through the blood vessels connecting our tongue, delivering the drug into the blood circulation system. As this route bypasses the stomach, almost 100% drug in its active form is delivered, allowing one to reap all the health benefits of the product. 
 
**How is Turmgel different from other available Curcumin products?** 
Turmgel is the only product that contains the purest form of whole turmeric extract, delivered in the form of a buccal dissolving lozenge. It is a special formulation developed using Quicksorb Hydrogel Technology. Turmeric is highly hydrophobic and impermeable for its passage through the tiny cells and tissues of our body. The patented Quicksorb Technology renders this product soluble with our saliva, thereby keeping its bioactive ingredients intact, with all its therapeutic activity delivered into the bloodstream instantly.  The principle ingredient Curcumin is delivered in the blood at the fastest rate with Turmgel at the lowest dose of 100 milligrams, compared to all the other products available in the market. All other products use high doses of Curcumin in their formulation, as all these products pass through the gut, making the product poorly bioavailable due to the << First-Pass Effect>>. 
 
**What are the inherent limitations with the conventional oral Curcumin preparations?**  
The conventional formulations available are capsules containing Curcumin extract with minimum of 475 milligrams per capsule. There are many different variants available. All these products need to be taken with water, and do not bypass the gastric system. A few formulators have added solubilizors and other additives to improve solubility of Curcumin, however, these are not yet devoid of drawbacks such as: 
Poor absorption & low permeability of Curcumin
Rapid metabolism and  rapid elimination from the body resulting in poor bioavailability of Curcumin in blood and increased frequency of high daily doses to achieve therapeutic blood levels for health benefits.
Potential drug interactions with concomitant medicines, as all other concomitant medicines pass through the same route. 
Major reported side-effects with oral Curcumin products such as gastric irritation leading to treatment withdrawal.

Currently it just says collapsible tab

**Comment by ghost** [comment]
Added content
