### ISSUE TITLE
Hero image transition is buggy. Please do a cross-fade

### ISSUE THREAD

**Issue by alliv8** [iamjamielobo/turmgel-website#82]
![image](https://user-images.githubusercontent.com/1996761/27145943-2ab0e8f2-5155-11e7-9d86-ce310076d4f2.png)

The expectation was to do a cross fade between the the incoming and outgoing image, it's currently abruptly changing. @iamjamielobo put some code of the internet, which I then tried to make work, but still screwed up.

**Comment by alliv8** [comment]
I think instead of changing the src, there should be 3 images in the DOM, and we should fade them in and out

**Comment by ghost** [comment]
fixed
